version: '3.8'

services:
  annual-leave-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development # You can change this to production if needed
    volumes:
      - .:/app # Mount the current directory to /app in the container